### ISSUE TITLE
node . isn't working it get stuck and show no error 

### ISSUE THREAD

**Issue by KhanHamidkhan** [MarcMagdi/MiniChatService#1]

**Comment by MarcMagdi** [comment]
Can you provide more information?
1- Did you have any issues installing the node modules?
2- What is your version of nodejs & npm?
3- Did the issue was with the installation or running the node application?

**Comment by KhanHamidkhan** [comment]
node 6.11.0 and npm 5.4.2
I have installed it successfully but the issue is with running of node app

**Comment by MarcMagdi** [comment]
Make sure the connection to the Postgres database is created successfully.
Check the datasource.js in the server folder for authentication data

**Comment by KhanHamidkhan** [comment]
Could I use mongodb instead of postgres in your app ? if yes how ?

**Comment by MarcMagdi** [comment]
Yes, you can.
Refer to Loopback documentation for changing the Database source.
